import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

interface GeneratedArray {
  name: string;
  puzzles: Array<unknown>;
}

interface GeneratedOutputs {
  chunks: Array<{ filename: string; source: string }>;
  list: string;
  meta: string;
}

interface PuzzlePaths {
  outputDir?: string;
  rootDir?: string;
  sourcePath?: string;
}

let targetChunkCount = 4;
let generatedHeader =
  "// Generated by build.ts.\n" + "// Edit src/game/list.ts instead.\n\n";

export function extractPuzzleArrays(source: string): Array<GeneratedArray> {
  let arrayMatches = source.matchAll(
    /let\s+(demo|week\d+)\s*(?::[\s\S]*?)?=\s*(\[[\s\S]*?\]);/g,
  );

  return [...arrayMatches].map((match) => {
    let [, name, text] = match;
    return {
      name: name as string,
      puzzles: eval(text as string),
    };
  });
}

export function buildGeneratedOutputs(
  puzzles: Array<unknown>,
  options: {
    chunkDirectoryImport: string;
    typeImport: string;
  },
): GeneratedOutputs {
  let chunkSize = Math.ceil(puzzles.length / targetChunkCount);
  let chunkCount = Math.ceil(puzzles.length / chunkSize);
  let chunkDirectoryImport = options.chunkDirectoryImport.endsWith("/")
    ? options.chunkDirectoryImport.slice(0, -1)
    : options.chunkDirectoryImport;
  let chunks = Array.from({ length: chunkCount }, (_, index) => {
    let chunk = puzzles.slice(index * chunkSize, (index + 1) * chunkSize);
    return {
      filename: `list.chunk${index}.ts`,
      source:
        `${generatedHeader}` +
        `import type { Puzzle } from "${options.typeImport}";\n\n` +
        `export let puzzleChunk${index}: Array<Puzzle<string>> = ${JSON.stringify(
          chunk,
          null,
          2,
        )};\n`,
    };
  });

  let loaderImports = Array.from({ length: chunkCount }, (_, index) => {
    return `import { puzzleChunk${index} } from "${chunkDirectoryImport}/list.chunk${index}";`;
  }).join("\n");

  let chunkNames = Array.from({ length: chunkCount }, (_, index) => {
    return `puzzleChunk${index}`;
  }).join(",\n  ");

  return {
    chunks,
    list:
      `${generatedHeader}` +
      `import type { Puzzle } from "${options.typeImport}";\n` +
      `${loaderImports}\n\n` +
      `export let puzzles: Array<Puzzle<string>> = [\n  ${chunkNames}\n].flat();\n`,
    meta:
      `${generatedHeader}` +
      `export let puzzleChunkSize = ${chunkSize};\n` +
      `export let puzzleChunkCount = ${chunkCount};\n` +
      `export let puzzleCount = ${puzzles.length};\n`,
  };
}

export async function generatePuzzleFiles(paths?: {
  outputDir?: string;
  rootDir?: string;
  sourcePath?: string;
}) {
  let { outputDir, sourcePath } = resolvePuzzlePaths(paths);

  let source = await readFile(sourcePath, "utf8");
  let arrays = extractPuzzleArrays(source);

  if (!arrays.length) {
    throw new Error(`No puzzle arrays found in ${sourcePath}`);
  }

  let puzzles = arrays.flatMap((entry) => entry.puzzles);
  let outputs = buildGeneratedOutputs(puzzles, {
    chunkDirectoryImport: "./",
    typeImport: "../lib/types",
  });

  await mkdir(outputDir, { recursive: true });

  await Promise.all(
    outputs.chunks.map((chunk) =>
      writeFile(resolve(outputDir, chunk.filename), chunk.source),
    ),
  );
  await writeFile(resolve(outputDir, "list.ts"), outputs.list);
  await writeFile(resolve(outputDir, "list.meta.ts"), outputs.meta);
}

export function resolvePuzzlePaths(
  paths?: PuzzlePaths,
  moduleUrl = import.meta.url,
): Required<PuzzlePaths> {
  let defaultRootDir = dirname(fileURLToPath(moduleUrl));
  let rootDir = paths?.rootDir ?? defaultRootDir;

  return {
    outputDir: paths?.outputDir ?? resolve(rootDir, "src/.puzzles"),
    rootDir,
    sourcePath: paths?.sourcePath ?? resolve(rootDir, "src/game/list.ts"),
  };
}

export function shouldRunFromCli(
  argv = process.argv,
  moduleUrl = import.meta.url,
): boolean {
  return argv[1] != undefined && fileURLToPath(moduleUrl) == resolve(argv[1]);
}

export async function runCli(argv = process.argv, moduleUrl = import.meta.url) {
  if (shouldRunFromCli(argv, moduleUrl)) {
    await generatePuzzleFiles({
      rootDir: dirname(fileURLToPath(moduleUrl)),
    });
  }
}

await runCli();
